services:
  web:
    build: .
    restart: always
    ports:
      - 8080:8080
    links:
      - db:database
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
